"""section_summaries: weekly LLM paragraph per active section

One row per (section_id, week_start). Generated by weekly_review.py
(brain-weekly.timer, Sunday 20:00 IST). Activity = items captured that week.

Drill stats in the summary are notebook-scoped (drill_sessions.notebook_id);
section-level drill stats will flow once revision_questions.section_id
is populated via the notebook agent.

Revision ID: 036_section_summaries
Revises: 035_items_learned
Create Date: 2026-10-01
"""

revision      = "036_section_summaries"
down_revision = "035_items_learned"
branch_labels = None
depends_on    = None

import sqlalchemy as sa
from alembic import op


def upgrade() -> None:
    op.create_table(
        "section_summaries",
        sa.Column("id", sa.BigInteger(), sa.Identity(), primary_key=True),
        sa.Column("section_id", sa.BigInteger(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "generated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["section_id"], ["sections.id"],
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("section_id", "week_start", name="uq_section_summaries_section_week"),
    )
    op.create_index(
        "ix_section_summaries_section_id",
        "section_summaries",
        ["section_id"],
    )


def downgrade() -> None:
    op.drop_index("ix_section_summaries_section_id", table_name="section_summaries")
    op.drop_table("section_summaries")
